---

- name: "Clone project to {{ homestack_config.install_dir }}"
  git:
    repo: "{{ homestack_repo_url }}"
    clone: yes
    dest: "{{ homestack_config.install_source }}"

- name: Configure .env file
  template:
    src: env.j2  
    dest: "{{ homestack_config.install_source }}/.env"
