---
- name: Pull node-red image
  docker_compose:
    project_src: "{{ homestack_config.install_source }}"
    pull: yes
    state: absent
    services: node-red

- name: Ensure correct folders exist
  file:
    path: "{{ homestack_config.install_source }}/compose/{{ item }}/node-red"
    owner: root
    group: root
    mode: 0755
    state: directory
  loop:
    - data

- name: Hash user passwords
  shell: "{{ lookup('template', 'password_shell.j2') }}"
  loop: "{{ nodered_config.users }}"
  register: nodered_hashed_passwords

- debug:
    var: nodered_hashed_passwords

- name: Generate settings.js
  template:
    src: settings.js.j2
    dest: "{{ nodered_data_dir }}/settings.js"

- name: (re)start node-red container with compose
  docker_compose:
    project_src: "{{ homestack_config.install_source }}"
    state: present
    restarted: yes
    services: node-red
