---

- name: Pull mosquitto image
  docker_compose:
    project_src: "{{ homestack_config.install_source }}"
    pull: yes
    state: present
    services: mosquitto

- name: Ensure correct folders exist
  file:
    path: "{{ homestack_config.install_source }}/compose/{{ item }}/mosquitto"
    owner: root
    group: root
    mode: 0755
    state: directory
  loop:
    - conf
    - data
    - log

- name: Generate mosquitto.conf
  template:
    src: mosquitto.conf.j2
    dest: "{{ mosquitto_config_dir }}/mosquitto.conf"

- name: Generate users.passwd
  docker_container:
    image: eclipse-mosquitto
    name: mosquitto-password-gen
    auto_remove: yes
    mounts:
      - source: "{{ mosquitto_config_dir }}"
        target: "/config"
        type: bind
    user: root:root
    entrypoint: sh
    command: "{{ lookup('template', 'password_shell.j2') }}"

- name: (re)start mosquitto container with compose
  docker_compose:
    project_src: "{{ homestack_config.install_source }}"
    state: present
    restarted: yes
    services: mosquitto
