---

- name: Make sure /etc/udev/rules.d exists
  file:
    path: /etc/udev/rules.d
    state: directory
    owner: root
    mode: 644

- name: Install udev rules
  template:
    src: udev-template.rules.j2
    dest: "/etc/udev/rules.d/{{ item.priority }}-{{ item.filename }}.rules"
  loop: "{{ udev.rules }}"

- name: Reload & Trigger udev rules
  shell: "udevadm control --reload-rules && udevadm trigger"
